### ISSUE TITLE
[FEATURE]: Create WeatherService for mockablity and live

### ISSUE THREAD

**Issue by 0xLeif** [0xOpenBytes/OpenWeather#1]
### Description

- Weather service protocol
- Mock weather service implementation
- Live weather service implementation
- Local model

**Comment by haIIux** [comment]
This is out of my wheelhouse and stepping out of my comfort zone. If no one else would like to take this, I can make an attempt. Although I have one question:

> Live weather service implementation


Do we have an OpenBytes API Key available for use or should we use our own first?

**Comment by 0xLeif** [comment]
> Do we have an OpenBytes API Key available for use or should we use our own first?

This will use Apple's WeatherKit so it will be handled by provisioning profiles and capabilities. We will need to either set it up for our personal account and use different bundle ids per developer.. or use a single account for the bundle id.
